name: Trigger Webhook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook
      run: |
        curl -X POST -H 'X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}' http://wiki.batkomaepravo.org:5000/webhook
