name: Trigger Webhook

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook
      run: |
        curl -f -X POST -H 'X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}' http://wiki.batkomaepravo.org:5000/webhook
